### ISSUE TITLE
PDF页面右下角有字数显示的问题

### ISSUE THREAD

**Issue by Liberta-X** [ouc-ocean-group/oucthesis#10]
您好，我在使用您这个模板的时候，遇到了在PDF页面的右下角，会显示数字。且这个数字会随着文中字数的改变而改变。我猜测是count这部分出了问题，但是我无法解决。求助。
![image](https://user-images.githubusercontent.com/18180055/196966773-87f7ddf1-957c-42cf-a4b0-905d63ed6c35.png)

**Comment by GeoffreyChen777** [comment]
这就是正常的字数统计功能，如果你不想要，就在文件头去掉

https://github.com/ouc-ocean-group/oucthesis/blob/057a1b3090f6fec6d413396eb64d233f698b08a1/main.tex#L5

**Comment by Liberta-X** [comment]
好的  感谢
