### ISSUE TITLE
摘要加入目录中

### ISSUE THREAD

**Issue by Wj-creat** [ouc-ocean-group/oucthesis#11]
你好，我使用次模板后发现摘要的中文和英文都无法出现在目录中，于是我加入命令
\phantomsection\addcontentsline{toc}{section}{Abstract} %将摘要放进目录

但是，显示出现两个问题：
1）大小不对应
2）不对齐，没有顶格

![image](https://user-images.githubusercontent.com/63938384/207333994-3cad9d12-4c7d-4e9d-860e-4141b5e70c55.png)

请问，你是否有好的解决方案，希望得到帮助，万分感谢！

**Comment by GeoffreyChen777** [comment]
我不知道现在的模版要求是啥，我当年的时候，这两个章节是不应显示在目录的。

至于你想让他显示，我猜测是没有序号导致的吧。不过具体你可以自己研究一下吧，我离开学校已经太久了，没有人接手这个仓库的维护。

**Comment by GeoffreyChen777** [comment]
我刚才问了问，现在有个我原来的老师，有一个仓库，你可以去那里咨询咨询，本仓库就停止维护了哈

https://github.com/summitgao/OUC-LaTex-master
