### ISSUE TITLE
Mac下编译错误，报错：Undefined Control Sequence

### ISSUE THREAD

**Issue by ghost** [ouc-ocean-group/oucthesis#2]
你好，感谢分享模板。
Mac系统，MacTex 2021 + Texshop，使用xelatex编译，报错如下：
![image](https://user-images.githubusercontent.com/27879832/113673296-628fbc00-96eb-11eb-8cbe-42d7e054e063.png)

**Comment by GeoffreyChen777** [comment]
@liuyuanOUC 你好，我没有在MacTex下进行过测试，只在Texpad (Mac)、TexStudio、Overleaf上进行过测试。

如果您解决了这个问题，欢迎PR。

**Comment by gangw0632** [comment]
你好！我在Mac的Texlive下也存在这个问题，我使用的是基于Texlive的TexStudio。请问楼主这个问题已经解决了吗？谢谢！

**Comment by ghost** [comment]
@gangw0632 没有，使用word了。

**Comment by GeoffreyChen777** [comment]
> 你好！我在Mac的Texlive下也存在这个问题，我使用的是基于Texlive的TexStudio。请问楼主这个问题已经解决了吗？谢谢！

如果你是本科硕士的话，还是建议用word，因为当时我毕业的时候就是学校要求必须word导致后来又重新用word排版。

**Comment by GeoffreyChen777** [comment]
@liuyuanOUC @gangw0632 同学们你们好，由于听闻还在OUC的朋友们说，信院博士们可以使用LaTex了，于是我抽空维护了一下，现在最新版的Tex应该不会遇到报错了。我在 TexPad 和 Overleaf 上测试了～
