### ISSUE TITLE
TexLive切换为2020之后报错

### ISSUE THREAD

**Issue by ghost** [ouc-ocean-group/oucthesis#3]
请问如何让本模板支持TexLive 2020及更高版本?

在Overleaf平台将编译器设置为 XeLaTex，TeX Live 版本选择 2018, 编译成功.
在Overleaf平台将编译器设置为 XeLaTex，TeX Live 版本选择 2019, 编译成功.
在Overleaf平台将编译器设置为 XeLaTex，TeX Live 版本选择 2020, 编译超时.
在Windows上使用TexStudio+TexLive 2020, 编译失败, 其中TexStudio中设置编译器为XeLaTex.
在Windows上使用TexStudio+**TexLive 2019, 编译成功**, 其中TexStudio中设置编译器为XeLaTex.

以下内容为在Windows平台(TexLive2020)编译时的的日志
_Undefined control sequence. \ouc@strifeq
Missing \begin{document}.  #\ouc@strifeq{\ouc@fontset
Undefined control sequence. \ouc@strifeq
Package fontspec Error: The font "Menlo" cannot be found. }
Undefined control sequence. }
Package fontspec Error: The font "Menlo" cannot be found. }
Package fontspec Error: The font "Menlo" cannot be found. }
Undefined control sequence. }
Undefined control sequence. }
Undefined control sequence. \ouc@strifeq
Package fontspec Error: The font "Songti SC Light" cannot be found. ]{Songti SC}
Package fontspec Error: The font "Songti SC Light" cannot be found. ]{Songti SC}
Package fontspec Error: The font "Songti SC Light" cannot be found. ]{Songti SC}
Package fontspec Error: The font "Songti SC Bold" cannot be found. ]{Songti SC}
Package fontspec Error: The font "Songti SC Bold" cannot be found. ]{Songti SC}
Package fontspec Error: The font "Kaiti SC" cannot be found. ]{Songti SC}
Package fontspec Error: The font "Kaiti SC" cannot be found. ]{Songti SC}
Package fontspec Error: The font "Kaiti SC Bold" cannot be found. ]{Songti SC}
Package fontspec Error: The font "Kaiti SC Bold" cannot be found. ]{Songti SC}
Undefined control sequence. \ouc@strifeq
Undefined control sequence. \ouc@strifeq
Package fontspec Error: The font "AdobeSongStd-Light" cannot be found. ]{AdobeSongStd-Light}
Package fontspec Error: The font "AdobeSongStd-Light" cannot be found. ]{AdobeSongStd-Light}
Package fontspec Error: The font "AdobeSongStd-Light" cannot be found. ]{AdobeSongStd-Light}
Package fontspec Error: The font "AdobeSongStd-Light" cannot be found. ]{AdobeSongStd-Light}
Package fontspec Error: The font "AdobeSongStd-Light" cannot be found. ]{AdobeSongStd-Light}
Package fontspec Error: The font "AdobeKaitiStd-Regular" cannot be found. ]{AdobeSongStd-Light}
Package fontspec Error: The font "AdobeKaitiStd-Regular" cannot be found. ]{AdobeSongStd-Light}
Font TU/AdobeSongStd-Light(0)/m/n/9.03365=AdobeSongStd-Light/OT at 9.03365pt not loadable: Metric (TFM) file or installed font not found. \makeprepage
Package fontspec Error: The font "AdobeHeitiStd-Regular" cannot be found. \makeprepage
Package fontspec Error: The font "AdobeHeitiStd-Regular" cannot be found. \makeprepage
Package fontspec Error: The font "AdobeHeitiStd-Regular" cannot be found. \makeprepage
Package fontspec Error: The font "AdobeHeitiStd-Regular" cannot be found. \makeprepage
Package fontspec Error: The font "AdobeHeitiStd-Regular" cannot be found. \makeprepage
Font TU/AdobeHeitiStd-Regular(0)/m/n/18.06729=AdobeHeitiStd-Regular/OT at 18. \makeprepage
Missing number, treated as zero. \makeprepage
Illegal unit of measure (pt inserted). \makeprepage
Missing number, treated as zero. \makeprepage
Illegal unit of measure (pt inserted). \makeprepage
Missing number, treated as zero. \makeprepage
Illegal unit of measure (pt inserted). \makeprepage
Missing \endcsname inserted. \makeprepage
Missing number, treated as zero. \makeprepage
Illegal unit of measure (pt inserted). \makeprepage
Missing number, treated as zero. \makeprepage
Illegal unit of measure (pt inserted). \makeprepage
Extra \endcsname. \makeprepage
Improper alphabetic constant. \makeprepage
Illegal unit of measure (pt inserted). \makeprepage
Missing number, treated as zero. \makeprepage
Illegal unit of measure (pt inserted). \makeprepage
Package fontspec Error: The font "AdobeSongStd-Light" cannot be found. \makeprepage
Package fontspec Error: The font "AdobeSongStd-Light" cannot be found. \makeprepage
Package fontspec Error: The font "AdobeSongStd-Light" cannot be found. \makeprepage
Package fontspec Error: The font "AdobeSongStd-Light" cannot be found. \makeprepage
Package fontspec Error: The font "AdobeSongStd-Light" cannot be found. \makeprepage
Font TU/AdobeSongStd-Light(1)/m/n/12.04486=AdobeSongStd-Light/OT at 12.04486pt not loadable: Metric (TFM) file or installed font not found. \makeprepage
Missing number, treated as zero. \makeprepage
Illegal unit of measure (pt inserted). \makeprepage
Missing number, treated as zero. \makeprepage
Illegal unit of measure (pt inserted). \makeprepage
Missing number, treated as zero. \makeprepage
Illegal unit of measure (pt inserted). \makeprepage
Missing \endcsname inserted. \makeprepage
Missing number, treated as zero. \makeprepage
Illegal unit of measure (pt inserted). \makeprepage
Missing number, treated as zero. \makeprepage
Illegal unit of measure (pt inserted). \makeprepage
Extra \endcsname. \makeprepage
Improper alphabetic constant. \makeprepage
Illegal unit of measure (pt inserted). \makeprepage
Missing number, treated as zero. \makeprepage
Illegal unit of measure (pt inserted). \makeprepage
Missing number, treated as zero. \makeprepage
Illegal unit of measure (pt inserted). \makeprepage
Missing number, treated as zero. \makeprepage
Illegal unit of measure (pt inserted). \makeprepage
Missing number, treated as zero. \makeprepage
Illegal unit of measure (pt inserted). \makeprepage
Missing \endcsname inserted. \makeprepage
Missing number, treated as zero. \makeprepage
Illegal unit of measure (pt inserted). \makeprepage
Missing number, treated as zero. \makeprepage
Illegal unit of measure (pt inserted). \makeprepage
Extra \endcsname. \makeprepage
Improper alphabetic constant. \makeprepage
Illegal unit of measure (pt inserted). \makeprepage
Missing number, treated as zero. \makeprepage
Illegal unit of measure (pt inserted). \makeprepage
Missing number, treated as zero. \makeprepage
Illegal unit of measure (pt inserted). \makeprepage
Missing number, treated as zero. \makeprepage
Illegal unit of measure (pt inserted). \makeprepage
Missing number, treated as zero. \makeprepage
Illegal unit of measure (pt inserted). \makeprepage
Missing \endcsname inserted. \makeprepage
Missing number, treated as zero. \makeprepage
Illegal unit of measure (pt inserted). \makeprepage
Missing number, treated as zero. \makeprepage
Illegal unit of measure (pt inserted). \makeprepage
Extra \endcsname. \makeprepage
Improper alphabetic constant. \makeprepage
Illegal unit of measure (pt inserted). \makeprepage
Missing number, treated as zero. \makeprepage
Illegal unit of measure (pt inserted). \makeprepage
Font TU/AdobeSongStd-Light(0)/b/n/15.05608=AdobeSongStd-Light/OT:embolden=2; at 15.05608pt not loadable: Metric (TFM) file or installed font not found. \makeprepage
Font TU/AdobeSongStd-Light(0)/m/n/12.04486=AdobeSongStd-Light/OT at 12.04486pt not loadable: Metric (TFM) file or installed font not found. \makeprepage
Cannot use \XeTeXglyphbounds with nullfont; not a native platform font. \makeprepage
Cannot use \XeTeXglyphbounds with nullfont; not a native platform font. \makeprepage
Missing ) inserted for expression. \makeprepage
You can't use `\XeTeXcharglyph' in restricted horizontal mode. \makeprepage
Cannot use \XeTeXglyphbounds with nullfont; not a native platform font. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
Cannot use \XeTeXglyphbounds with nullfont; not a native platform font. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
Missing ) inserted for expression. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
You can't use `\XeTeXcharglyph' in restricted horizontal mode. \makeprepage
Cannot use \XeTeXglyphbounds with nullfont; not a native platform font. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
Cannot use \XeTeXglyphbounds with nullfont; not a native platform font. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
Missing ) inserted for expression. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
You can't use `\XeTeXcharglyph' in restricted horizontal mode. \makeprepage
Cannot use \XeTeXglyphbounds with nullfont; not a native platform font. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
Cannot use \XeTeXglyphbounds with nullfont; not a native platform font. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
Missing ) inserted for expression. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
You can't use `\XeTeXcharglyph' in restricted horizontal mode. \makeprepage
Cannot use \XeTeXglyphbounds with nullfont; not a native platform font. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
Cannot use \XeTeXglyphbounds with nullfont; not a native platform font. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
Missing ) inserted for expression. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
You can't use `\XeTeXcharglyph' in restricted horizontal mode. \makeprepage
Cannot use \XeTeXglyphbounds with nullfont; not a native platform font. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
Cannot use \XeTeXglyphbounds with nullfont; not a native platform font. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
Missing ) inserted for expression. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
You can't use `\XeTeXcharglyph' in restricted horizontal mode. \makeprepage
Cannot use \XeTeXglyphbounds with nullfont; not a native platform font. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
Cannot use \XeTeXglyphbounds with nullfont; not a native platform font. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
Missing ) inserted for expression. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
You can't use `\XeTeXcharglyph' in restricted horizontal mode. \makeprepage
Cannot use \XeTeXglyphbounds with nullfont; not a native platform font. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
Cannot use \XeTeXglyphbounds with nullfont; not a native platform font. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
Missing ) inserted for expression. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
You can't use `\XeTeXcharglyph' in restricted horizontal mode. \makeprepage
Cannot use \XeTeXglyphbounds with nullfont; not a native platform font. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
Cannot use \XeTeXglyphbounds with nullfont; not a native platform font. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
Missing ) inserted for expression. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
You can't use `\XeTeXcharglyph' in restricted horizontal mode. \makeprepage
Cannot use \XeTeXglyphbounds with nullfont; not a native platform font. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
Cannot use \XeTeXglyphbounds with nullfont; not a native platform font. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
Missing ) inserted for expression. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
You can't use `\XeTeXcharglyph' in restricted horizontal mode. \makeprepage
Cannot use \XeTeXglyphbounds with nullfont; not a native platform font. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
Cannot use \XeTeXglyphbounds with nullfont; not a native platform font. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
Missing ) inserted for expression. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
You can't use `\XeTeXcharglyph' in restricted horizontal mode. \makeprepage
Cannot use \XeTeXglyphbounds with nullfont; not a native platform font. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
Cannot use \XeTeXglyphbounds with nullfont; not a native platform font. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
Missing ) inserted for expression. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
You can't use `\XeTeXcharglyph' in restricted horizontal mode. \makeprepage
Cannot use \XeTeXglyphbounds with nullfont; not a native platform font. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
Cannot use \XeTeXglyphbounds with nullfont; not a native platform font. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
Missing ) inserted for expression. \makeprepage
LaTeX3 Error: Control sequence(LaTeX3) already defined. \makeprepage
You are using Fandol font family.
Using \overbracket and \underbracket from(unicode-math) `mathtools' package.
I'm going to overwrite the following commands(unicode-math) from the `mathtools' package: (unicode-math) (unicode-math) \dblcolon, \coloneqq, \Coloneqq, \eqqcolon._

**Comment by debeetle** [comment]
我也在Overleaf平台遇到相同问题，不同的是我切换所有版本都没有成功，请问您找到解决办法了吗？期待回答

**Comment by GeoffreyChen777** [comment]
> 我也在Overleaf平台遇到相同问题，不同的是我切换所有版本都没有成功，请问您找到解决办法了吗？期待回答

@debeetle 

我刚试了一下，
<img width="246" alt="image" src="https://user-images.githubusercontent.com/14183213/181523595-ee1a6b4b-bf71-4e9c-99e4-59698521b7c9.png">
按照这样，没问题啊。

**Comment by debeetle** [comment]
我是另一个模版，google到这个issue下，我想问问之前这个人问题有没有解决，打扰到您我表示十分抱歉

**Comment by ghost** [comment]
> 我也在Overleaf平台遇到相同问题，不同的是我切换所有版本都没有成功，请问您找到解决办法了吗？期待回答

下载最新的模板试试.
我之前使用的是1.0.0版本, 在TexLive2020上会报错.
使用最新的1.2.3版本不报错.

**Comment by ghost** [comment]
> > 我也在Overleaf平台遇到相同问题，不同的是我切换所有版本都没有成功，请问您找到解决办法了吗？期待回答
> 
> @debeetle
> 
> 我刚试了一下， <img alt="image" width="246" src="https://user-images.githubusercontent.com/14183213/181523595-ee1a6b4b-bf71-4e9c-99e4-59698521b7c9.png"> 按照这样，没问题啊。

最新的1.2.3版本已经不存在这个问题了.
