### ISSUE TITLE
下载后texstudio无法编译

### ISSUE THREAD

**Issue by meatless-tim** [ouc-ocean-group/oucthesis#5]
您好，我下载之后打开main.tex无法编译，不知道是什么情况。

**Comment by GeoffreyChen777** [comment]
> 

你好请问你是用什么环境什么软件进行的编译

**Comment by meatless-tim** [comment]
你好，我用的是texlive+texstudio的组合。

GeoffreyChen777 ***@***.***>于2021年12月24日 周五19:21写道：

**Comment by GeoffreyChen777** [comment]
@meatless-tim 能提供一些报错的信息么

**Comment by meatless-tim** [comment]
你好，报错信息如下，
0. File `words.count' not found. \chapter
1. Using \overbracket and \underbracket from(unicode-math) `mathtools'
package.
2. I'm going to overwrite the following commands(unicode-math) from the
`mathtools' package: (unicode-math) (unicode-math) \dblcolon, \coloneqq,
\Coloneqq, \eqqcolon.
3. Token not allowed in a PDF string (Unicode):(hyperref) removing
`\zhspace'
[image: image.png]

GeoffreyChen777 ***@***.***> 于2021年12月24日周五 19:29写道：

**Comment by GeoffreyChen777** [comment]
@meatless-tim 请问是启用了字数统计么？如果不启用还会报错么？

**Comment by meatless-tim** [comment]
我应该没有启用，就是刚下载你们的模板，然后尝试编译，直接报错，没有设置其它的。

GeoffreyChen777 ***@***.***> 于2021年12月24日周五 19:36写道：

**Comment by GeoffreyChen777** [comment]
@meatless-tim 模版默认是启用了的，所以如果想要使用字数统计，请参照 

https://github.com/ouc-ocean-group/oucthesis/blob/master/README.md#%E5%AD%97%E6%95%B0%E7%BB%9F%E8%AE%A1

进行相关设置，如果不使用字数统计，请在main.tex头部选项部分去掉 count 选项

https://github.com/ouc-ocean-group/oucthesis/blob/7511d7a415a8e73d16037f4d76954006fb9b207e/main.tex#L1

**Comment by meatless-tim** [comment]
可以了，感谢大佬！

GeoffreyChen777 ***@***.***>于2021年12月24日 周五19:44写道：

**Comment by GeoffreyChen777** [comment]
@meatless-tim 不客气。
