### ISSUE TITLE
目录条目颜色的问题

### ISSUE THREAD

**Issue by gangw0632** [ouc-ocean-group/oucthesis#7]
尊敬的作者辛苦了！能给我们提供这样的一个模板来使用好开心，节约了好多时间和精力来排版。我注意到目录条目颜色为蓝色，但是我周围用word的同学他们的目录都是黑色，作者可否出一个新的branch或者直接cls文件作出修改呢？谢谢！

**Comment by GeoffreyChen777** [comment]
蓝色是因为有超链接的版本方便电脑阅读，你在提交的时候在main.tex最开始选择print去掉pdf就可以了。
https://github.com/ouc-ocean-group/oucthesis/blob/057a1b3090f6fec6d413396eb64d233f698b08a1/main.tex#L4
