### ISSUE TITLE
是否可以加入新的包latex 算法包algorithm2e 

### ISSUE THREAD

**Issue by ZFeiXQ** [ouc-ocean-group/oucthesis#8]
感谢作者提供的模板，是否可以扩展该模支持算法包algorithm2e，修改以后发现有些不兼容

**Comment by GeoffreyChen777** [comment]
请提供报错信息

**Comment by ZFeiXQ** [comment]
我注释了原有的算法包，并添加代码\RequirePackage[ruled,linesnumbered]{algorithm2e}，运行可以正常显示，但是报错，主要错误如下
![image](https://user-images.githubusercontent.com/42347369/168775534-dc304f36-a7ca-49f7-8d40-d85d30613a59.png)
其中，主要错误是致谢部分，其他部分因该是algorithm2e不适合algorithm设置的代码

**Comment by GeoffreyChen777** [comment]
我简单试了下，需要修改的地方挺多的，目前暂时没有精力去做大批量修改，请尝试用 `algorithm algorithmicx` 完成公式。

除了在这里引用了算法包
https://github.com/ouc-ocean-group/oucthesis/blob/057a1b3090f6fec6d413396eb64d233f698b08a1/main.tex#L25-L26

在模版文件里也引用了，因为在模版文件里设置了相关的 Caption 计数符号：
https://github.com/ouc-ocean-group/oucthesis/blob/057a1b3090f6fec6d413396eb64d233f698b08a1/oucthesis.cls#L64-L65

如果你必须需要`algorithm2e`请尝试自己修改试试，欢迎PR。
