### ISSUE TITLE
请问OUC thesis latex模板能否设置成pdflatex编译

### ISSUE THREAD

**Issue by meatless-tim** [ouc-ocean-group/oucthesis#9]
你好, xelatex的编译速度太慢了,能否将编译模式改为pdflatex?

似乎在cls文件中限制了只能使用Xelatex。

**Comment by GeoffreyChen777** [comment]
pdflatex 很难支持中文。这也是为什么各学校的模版都是xelatex。

**Comment by meatless-tim** [comment]
主要是看见这个里面有写关于如何用pdflatex编译中文的。
https://blog.csdn.net/z_feng12489/article/details/90449495
但是我尝试在你们的模板中使用，提示cls中要求使用xelatex编译，所以我在想，能不能加上上述命令后，修改cls，然后就可以使用xelatex编译了。

GeoffreyChen777 ***@***.***> 于2022年9月26日周一 15:06写道：

**Comment by GeoffreyChen777** [comment]
你可以试着去尝试，但是大量命令都需要xelatex，我认为很难。

**Comment by meatless-tim** [comment]
行吧，我试试，我以为你们之前试过所以想着先问问你， so sad.

GeoffreyChen777 ***@***.***>于2022年9月26日 周一15:11写道：
